variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
  - task: Cache@2
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)
    displayName: Cache pnpm

  - script: |
      curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"
  - script: |
      pnpm install
    displayName: "Install pnpm"
  - script: |
      pnpm eslint 'src/**/*{.ts,.tsx}'
    displayName: "Eslint check"
  - script: |
      pnpm prettier -c .
    displayName: "Prettier check"
  - script: |
      pnpm test:ci
    displayName: "Testing files"
  - script: |
      pnpm build
    displayName: "Typescript and build"
